In [3]:
import gym
import numpy as np
import random
import time
from IPython.display import clear_output

In [19]:
env = gym.make('FrozenLake-v0')

In [20]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

print(action_space_size)
print(state_space_size)

4
16


In [21]:
num_episodes = 10000
max_steps_per_episode = 100
exploration_rate = 1
max_eploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01

discount_rate = 0.99
learning_rate = 0.1

In [22]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):

        # Exploration-exploitation trade-off
        exploration_rate_threshold = np.random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)
        if done:
            target = reward
        else:
            target = reward + discount_rate * np.max(q_table[new_state, :])
        q_table[state, action] = (1 - learning_rate) * q_table[state, action] + \
                                 learning_rate * target

        state = new_state
        rewards_current_episode += reward

        if done:
            break

    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
                       (max_eploration_rate - min_exploration_rate) * \
                       np.exp(-exploration_decay_rate * episode)

    rewards_all_episodes.append(rewards_current_episode)



In [23]:
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),
                                         num_episodes/1000)
count = 1000
print('********Average reward per thousand episodes********\n')
for r in rewards_per_thousand_episodes:
    print(count, ': ', str(sum(r/1000)))
    count += 1000

print('\n\n********Q-table********\n')
print(q_table)


********Average reward per thousand episodes********

1000 :  0.07700000000000005
2000 :  0.33600000000000024
3000 :  0.2450000000000002
4000 :  0.3950000000000003
5000 :  0.32500000000000023
6000 :  0.3970000000000003
7000 :  0.4960000000000004
8000 :  0.6420000000000005
9000 :  0.6810000000000005
10000 :  0.6920000000000005


********Q-table********

[[0.5358805  0.42962859 0.41046748 0.45182677]
 [0.20044216 0.11782158 0.19210018 0.40381519]
 [0.33404697 0.18521746 0.13971022 0.16940204]
 [0.14247088 0.         0.         0.        ]
 [0.55100465 0.3600674  0.43870298 0.27953868]
 [0.         0.         0.         0.        ]
 [0.20030695 0.13138215 0.14531869 0.14113524]
 [0.         0.         0.         0.        ]
 [0.36660346 0.50672302 0.44959188 0.58437999]
 [0.39475587 0.60472482 0.48291616 0.41370425]
 [0.53612462 0.28836282 0.2791905  0.19421684]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.40576002 0.59465366 0.76400983

In [30]:
for episode in range(3):
    state = env.reset()
    done = False
    print('*****EPISODE ', episode + 1, '*****\n\n\n')
    time.sleep(1)

    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)

        action = np.argmax(q_table[state, :])
        new_state, reward, done, info = env.step(action)

        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print('****You reached the goal!*****')
                time.sleep(3)
            else:
                print('****You fell through a hole!*****')
                time.sleep(3)
            clear_output(wait=True)
            break

        state = new_state

env.close()


  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!*****
